### ISSUE TITLE
Build and release the package with the addition of darwin_arm64

### ISSUE THREAD

**Issue by richardmcmillen** [plukevdh/terraform-provider-dmsnitch#11]
Thanks for this provider! I am working on a team with a mix of new M1 apple laptops and old intel ones. Having an official package built and released for `darwin_arm64`, would really help the workflow.

We can use something like https://github.com/kreuzwerker/m1-terraform-provider-helper to build for darwin_arm64 but it isn't great for collaboration as this removes any other platforms from the generated terraform.lock file meaning you have to munge it yourself to collaborate across platforms.

**Comment by ismith** [comment]
Given use of goreleaser, this should be a fairly minimal PR. (I'd put in a vote for linux_arm64 too ...)

**Comment by sydorovdmytro** [comment]
Hello @plukevdh, 
we could use this PR for a new release https://github.com/plukevdh/terraform-provider-dmsnitch/pull/12 (if it will be merged of course).

**Comment by plukevdh** [comment]
I added the updates from #12. I'd prefer seeing the changes requested in this issue as a separate PR. Thanks

**Comment by sydorovdmytro** [comment]
I think we don't really need anything specific to publish arm64 binaries, we've built them in [our forked project](https://github.com/Bonial-International-GmbH/terraform-provider-dmsnitch/releases/tag/v0.3.0) and everything works just fine on M1 laptops.

**Comment by richardmcmillen** [comment]
@plukevdh apologies if I have the wrong end of the stick but now that https://github.com/plukevdh/terraform-provider-dmsnitch/pull/12 is merged I'm not sure there is anything needed other than run through the release process for the next version.

It looks like until go 1.16 goreleaser didn't build for darwin/arm64. There is some mention of this here https://github.com/goreleaser/goreleaser/issues/1952 and in 1.16 release notes https://go.dev/blog/go1.16

So if you were to cut a new version and run the release process I think this should create and push a darwin/arm64 version.

**Comment by plukevdh** [comment]
@richardmcmillen Thanks for that clarification. I was confused as to what you all wanted done. I’ll cut a new version shortly. Thanks again for contributing!

**Comment by richardmcmillen** [comment]
Hi @plukevdh, no problem, and thanks for being happy to make a new release. Have you had time to make the release yet or is there something blocking it we can help with?

**Comment by plukevdh** [comment]
@richardmcmillen Many apologies. I've been in the middle of a SOC audit and transitioning to a new job so my brain is spaghetti. Let me do this now.

**Comment by plukevdh** [comment]
New tag and release cut. [v0.1.3](https://github.com/plukevdh/terraform-provider-dmsnitch/releases/tag/v0.1.3) includes changes for the arch builds. Let me know if you want anything else done, and thanks again for pushing this forward.

**Comment by flux-ricky** [comment]
Thanks heaps! FWIW I didn't know that this would require a golang upgrade when I opened it but I am glad it worked out. I've verified this is working for us now, cheers.

**Comment by richardmcmillen** [comment]
Thanks heaps! FWIW I didn't know that this would require a golang upgrade when I opened it but I am glad it worked out. I've verified this is working for us now, cheers.
