### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by keepclean** [plukevdh/terraform-provider-dmsnitch#3]
Hello,

Could you please clarify under which licence this provider has been published?
If possible, it would be very great if licence would be added to the repo as well.

Thank you.

**Comment by plukevdh** [comment]
I got your email. I had not been paying attention to GitHub, so thanks for reaching out. Repo is now licensed under MPL-2.0

**Comment by keepclean** [comment]
Thank you very much @plukevdh ! 👍
