### ISSUE TITLE
alert_email field missing from API calls

### ISSUE THREAD

**Issue by richarddouglasfrye** [plukevdh/terraform-provider-dmsnitch#8]
The dead man's snitch API has an alert_email field that needs to be added to this terraform module. See https://deadmanssnitch.com/docs/api/v1#creating-a-snitch

**Comment by jackie-ob** [comment]
We would also love to see this issue resolved.

**Comment by yurrriq** [comment]
Any thoughts, @plukevdh? Is this project still maintained?

**Comment by plukevdh** [comment]
@yurrriq it is, but only lightly. I've kind of maintained on an as-needed basis. Feel free to open a PR with the requisite fields added

**Comment by plukevdh** [comment]
@yurrriq @jackie-ob I forgot there was a PR open with some changes for this, but I gave feedback that was never addressed. Feel free to revise and re-submit under your own names if needed.
